version: '3.2'

services:
  app:
    build: .
    volumes:
      - /etc/passwd:/etc/passwd:cached
      - /etc/group:/etc/group:cached
      - .:/app:cached
    env_file:
      - "./.env"
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - "./pg_data/:/var/lib/postgresql/data"
      - "./postgresql.conf:/etc/postgresql/postgresql.conf"
    env_file:
      - "./.env"
    ports:
    - "5432:5432"
