version: '3.7'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app:cached
    env_file:
      - "./.env"
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - "./resources/postgres/pg_data/:/var/lib/postgresql/data"
      - "./resources/postgres/postgresql.conf:/etc/postgresql/postgresql.conf"
    env_file:
      - "./.env"
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
